Repository kubernetes-sigs/kubectl-validate, pull requests merged in 2023-05, with the labels that each got.

#3 chore: replace ioutil.ReadFile by os.ReadFile
  pkg/cmd/validate.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#6 fix: check errors in validate test
  pkg/cmd/validate_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#8 move main to root module
  main.go
  main_test.go
  pkg/cmd/validate.go
Labels: cncf-cla: yes, approved, size/XS

#11 chore: add golangci-lint config
  .golangci.yml
Labels: cncf-cla: yes, size/XS

#9 add readme
  README.md
Labels: cncf-cla: yes, size/L, approved

#19 chore: add ci workflow
  .github/workflows/ci.yaml
  .github/workflows/golangci-lint.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm

#21 fix unit tests
  main_test.go
  pkg/cmd/validate.go
  pkg/cmd/validate_test.go
  pkg/openapiclient/overlay.go
  pkg/openapiclient/patches/1.23/api/v1.json
  testcases/crds/jobset.yaml
  testcases/manifests/error_api_deprecation.yaml.disabled
  testcases/manifests/error_array_instead_of_map.yaml
  testcases/manifests/error_cel_basic.yaml
  testcases/manifests/error_cel_basic_multiple.yaml
  testcases/manifests/error_crd_typo.yaml
  testcases/manifests/error_enum_invalid.yaml
  testcases/manifests/error_indentation.yaml
  testcases/manifests/error_invalid_kind.yaml
  testcases/manifests/error_invalid_label.yaml
  testcases/manifests/error_invalid_name.yaml
  testcases/manifests/error_invalid_protocol_type.yaml
  testcases/manifests/error_map_instead_of_array.yaml
  testcases/manifests/error_missing_image.yaml
  testcases/manifests/error_missing_image_deployment.yaml.disabled
  testcases/manifests/error_missing_name.yaml
  testcases/manifests/error_misspelled_key.yaml
  testcases/manifests/error_quantity.yaml
  testcases/manifests/error_x_list_map_default.yaml
  testcases/manifests/error_x_list_map_duplicate_key.yaml
  testcases/manifests/jobset.yaml
  testcases/manifests/x_list_map_nonduplicate_key.yaml
Labels: cncf-cla: yes, size/L, approved

#10 feat: add recursive file loading support
  pkg/cmd/validate.go
  pkg/cmd/validate_test.go
  pkg/openapiclient/local_crds.go
  pkg/utils/files.go
  pkg/utils/files_test.go
  pkg/utils/testdata/a/a.json
  pkg/utils/testdata/a/a.pdf
  pkg/utils/testdata/a/a.yaml
  pkg/utils/testdata/a/a.yml
  pkg/utils/testdata/b/b.json
  pkg/utils/testdata/b/b.pdf
  pkg/utils/testdata/b/b.yaml
  pkg/utils/testdata/b/b.yml
Labels: cncf-cla: yes, size/L, approved, lgtm

#30 fix test to use 1.27, but point patches to 1.23
  pkg/cmd/validate_test.go
Labels: cncf-cla: yes, size/S, approved

#27 chore: run go test in ci workflow
  .github/workflows/ci.yaml
Labels: cncf-cla: yes, tide/merge-method-squash, approved, size/XS, lgtm

#26 fix: local files client
  pkg/openapiclient/local_files.go
Labels: cncf-cla: yes, tide/merge-method-squash, size/S, approved, lgtm

#33 decode crds to apiextensionsv1
  pkg/openapiclient/local_files.go
Labels: cncf-cla: yes, size/S, approved

#29 Add required job
  .github/workflows/ci.yaml
  .github/workflows/golangci-lint.yaml
Labels: cncf-cla: yes, approved, size/M

#31 fix: split dir flags for schemas and crds
  README.md
  pkg/cmd/validate.go
  pkg/cmd/validate_test.go
Labels: cncf-cla: yes, approved, size/M, lgtm

#35 add fallback client
  pkg/cmd/validate.go
  pkg/openapiclient/fallback.go
  pkg/openapiclient/overlay.go
Labels: cncf-cla: yes, approved, size/M

#37 fix: local files client
  pkg/openapiclient/local_files.go
Labels: cncf-cla: yes, tide/merge-method-rebase, approved, size/XS, lgtm

#41 Add kubectl-validate slack link to readme
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#40 feat: allow using fs in local files client
  pkg/cmd/validate.go
  pkg/openapiclient/local_crds.go
  pkg/openapiclient/local_files.go
  pkg/openapiclient/local_helpers.go
  pkg/openapiclient/overlay.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#45 fix: incorrect check in local file clients
  pkg/openapiclient/local_crds.go
  pkg/openapiclient/local_files.go
  pkg/openapiclient/overlay.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#48 chore: clean commented code
  pkg/utils/yaml.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#49 refactor: move fs helpers in utils package
  pkg/openapiclient/local_crds.go
  pkg/openapiclient/local_files.go
  pkg/openapiclient/overlay.go
  pkg/utils/files.go
  pkg/utils/fs.go
Labels: cncf-cla: yes, approved, size/M, lgtm

#46 test: add unit test for local crds client
  pkg/openapiclient/local_crds.go
  pkg/openapiclient/local_crds_test.go
  pkg/validatorfactory/factory.go
  testcases/crds/cert-manager.crds.yaml
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#51 refactor: introduce groupversion package
  pkg/openapiclient/composite.go
  pkg/openapiclient/github_builtins.go
  pkg/openapiclient/groupversion/composite.go
  pkg/openapiclient/groupversion/file.go
  pkg/openapiclient/groupversion/http.go
  pkg/openapiclient/groupversion/openapi.go
  pkg/openapiclient/groupversion/overlay.go
  pkg/openapiclient/hardcoded_builtins.go
  pkg/openapiclient/local_crds.go
  pkg/openapiclient/local_crds_test.go
  pkg/openapiclient/local_files.go
  pkg/openapiclient/overlay.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#53 refactor: rename localFilesClient to localSchemasClient and don't consider CRDs
  pkg/cmd/validate.go
  pkg/openapiclient/github_builtins_test.go
  pkg/openapiclient/local_files.go
  pkg/openapiclient/local_schemas.go
  pkg/openapiclient/local_schemas_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm
