Repository kubernetes-sigs/kubectl-validate, pull requests merged in 2024-04, with the labels that each got.

#108 fix --context typo in readme
  README.md
Labels: cncf-cla: yes, kind/documentation, approved, size/XS, lgtm

#101 Allow `--local-crds` flag to receive multiple values
  pkg/cmd/validate.go
  pkg/openapiclient/local_crds.go
  pkg/openapiclient/local_crds_test.go
  pkg/validator/factory_test.go
  testcases/more-crds/dnsendpoints.yaml
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#118 ignore non-crds given in crds directory
  pkg/openapiclient/local_crds.go
  testcases/crds/not-a-crd-should-be-ignored.yaml
Labels: kind/bug, cncf-cla: yes, approved, size/M, lgtm

#116 add apiregistration schema
  cmd/download-builtin-schemas/main.go
  pkg/openapiclient/builtins/1.23/apis/apiregistration.k8s.io/v1.json
  pkg/openapiclient/builtins/1.24/apis/apiregistration.k8s.io/v1.json
  pkg/openapiclient/builtins/1.25/apis/apiregistration.k8s.io/v1.json
  pkg/openapiclient/builtins/1.26/apis/apiregistration.k8s.io/v1.json
  pkg/openapiclient/builtins/1.27/apis/apiregistration.k8s.io/v1.json
  pkg/openapiclient/local_schemas_test.go
  testcases/manifests/apiservice.yaml
Labels: kind/bug, cncf-cla: yes, size/XXL, approved, lgtm

#113 Ignore empty documents.
  pkg/utils/yaml.go
  testcases/manifests/empty.yaml
  testcases/manifests/empty_with_document.yaml
Labels: kind/bug, cncf-cla: yes, size/S, approved, lgtm

#120 chore: add windows tests
  .github/workflows/ci.yaml
  pkg/cmd/validate.go
  pkg/openapiclient/github_builtins_test.go
  pkg/openapiclient/groupversion/file.go
  pkg/openapiclient/hardcoded_builtins.go
  pkg/openapiclient/local_crds.go
  pkg/openapiclient/local_crds_test.go
  pkg/openapiclient/local_schemas.go
  pkg/openapiclient/local_schemas_test.go
  pkg/openapiclient/overlay.go
  pkg/utils/files.go
  pkg/utils/fs.go
  pkg/validator/factory_test.go
  pkg/validator/schema_patcher.go
  pkg/validator/structural.go
Labels: cncf-cla: yes, size/L, tide/merge-method-squash, approved, lgtm
